version: "3"

services:
  express_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/etc/nginx/html/index.html:ro
    depends_on:
      - express_app
